args:
  slides_dir: '../slides'   # Directory where .svs/.ndpi/.tiff files are stored
  masks_dir:  './masks'    # Directory where you want to store the .h5 and .pt files containing patch features
  ext:  'svs'
  file_list_txt: null  # Include a txt file containing the full path of the specific slides. 
                        # Otherwise, it will process all the slides in the slides_dir

segmentation_args:
  checkpoint_path: '../checkpoints/'
  model: '../PathProfiler/tissue_segmentation/checkpoint_ts.pth' # checkpoint to the PathProfiler model
  mask_magnification: 2.5 # Mask magnification
  mpp_level_0: null # Mpp level 0
  #gpu_id : '0'
  patch_size_segmentation: 512 # Size of patches used to split the input WSI
                               # into smaller regions that can be processed; this 
                               # differs from the output dimension of the patching step
  batch_size: 1


patching_args:
  patches_dir: './patches'
  tile_size:   128    # Size of the output patches (NXN)
  save_thumbnails: True # Whether to save thumbnails of patched WSIs
  thumbnails_dir: './thumbnails' # Directory where thumbnails will be eventually stored